name: Deploy to Firebase Hosting on merge
"on":
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Create .env file
              run: |
                  echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" > .env
                  echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }}" > .env
                  echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}" > .env
                  echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }}" > .env
                  echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID }}" > .env
                  echo "VITE_APP_ID=${{ secrets.APP_ID }}" > .env
            - uses: actions/checkout@v4
            - run: npm install && npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMILE_SIGN_411812 }}"
                  channelId: live
                  projectId: smile-sign-411812
