name: Deploy to Firebase Hosting on merge

on:
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Create .env file
              run: |
                  echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env
                  echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }}" >> .env
                  echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}" >> .env
                  echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }}" >> .env
                  echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID }}" >> .env
                  echo "VITE_APP_ID=${{ secrets.VITE_APP_ID }}" >> .env
                  echo "VITE_HYPER_FORM_URL=${{ secrets.VITE_HYPER_FORM_URL }}" >> .env
                  cat .env
            - uses: actions/checkout@v4
            - run: npm install && npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMILE_SIGN_411812 }}"
                  channelId: live
                  projectId: smile-sign-411812

    slackNotification:
        needs: build_and_deploy
        name: Slack-Notification
        runs-on: ubuntu-latest
        env:
            SLACK_USERNAME: DeployBot
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # 成功
            - name: Slack Notification on Success
              uses: rtCamp/action-slack-notify@v2
              if: ${{ success() }}
              env:
                  SLACK_TITLE: Deploy / Success
                  SLACK_COLOR: good
                  SLACK_MESSAGE: Successfully deployed to Firebase🚀

            # 失敗
            - name: Slack Notification on Failure
              uses: rtCamp/action-slack-notify@v2
              if: ${{ failure() }}
              env:
                  SLACK_TITLE: Deploy / Failure
                  SLACK_COLOR: danger
                  SLACK_MESSAGE: Deployment to Firebase failed🥺
